Default: &defaults
  host: "localhost"
  port: 3000
  title: "Milagos Development"
  #analytics: for example, UA-12345678-9
  #theme: "carbonated"

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  # set this to the approot of your production installation
  approot: "http://www.example.com"
  # if running behind a reverse proxy, include something like
  # host: "127.0.0.1"
  # port: 8003
  # to only accept connections from localhost on port 8003
  <<: *defaults
